application: your_application_name
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon.ico
  static_dir: static/images

- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images

- url: /static/js/custom.js
  static_files: static/js/custom.js
  upload: static/js/custom.js

- url: /mapreduce(/.*)?
  script: mapreduce/main.py

- url: /.*
  script: fetcher_main.py
